import { Patient } from '../types';
import {
  ExplainableAiResult,
  ClinicalReasoningItem,
  FeatureContribution,
  EvidenceParameter,
  ConfidenceAnalysis,
  MissingInformationItem,
  GuidelineMatchItem,
  NextBestAction,
  PatientExplanation,
  DoctorExplanation,
} from '../types/explainableAi';

export class ExplainableAiEngine {
  private static instance: ExplainableAiEngine;

  private constructor() {}

  public static getInstance(): ExplainableAiEngine {
    if (!ExplainableAiEngine.instance) {
      ExplainableAiEngine.instance = new ExplainableAiEngine();
    }
    return ExplainableAiEngine.instance;
  }

  public static MANDATORY_DISCLAIMER =
    'This analysis is generated by HealthSense AI as a clinical decision support tool. Final diagnosis and treatment decisions remain the responsibility of the qualified healthcare professional.';

  public generateExplanation(
    patient: Patient,
    selectedDisease: string = 'Type 2 Diabetes',
    customVitals?: any
  ): ExplainableAiResult {
    const vitals = {
      bpSystolic: customVitals?.bpSystolic ?? patient.vitals?.bpSystolic ?? 138,
      bpDiastolic: customVitals?.bpDiastolic ?? patient.vitals?.bpDiastolic ?? 88,
      bmi: customVitals?.bmi ?? patient.vitals?.bmi ?? 28.4,
      hba1c: customVitals?.hba1c ?? patient.vitals?.hba1c ?? 7.2,
      glucose: customVitals?.glucose ?? patient.vitals?.glucose ?? 132,
      ldl: customVitals?.ldl ?? patient.vitals?.ldl ?? 142,
      weightKg: customVitals?.weightKg ?? patient.vitals?.weightKg ?? 84,
      heartRate: customVitals?.heartRate ?? patient.vitals?.heartRate ?? 76,
    };

    const age = patient.age || 54;
    const diseaseName = selectedDisease;

    // Generate Disease-Specific Reasoning & Features
    switch (diseaseName) {
      case 'Hypertension / ASCVD':
      case 'Hypertension':
      case 'Essential Hypertension':
        return this.generateHypertensionExplanation(patient, vitals, age);

      case 'Atherosclerotic CVD':
      case 'ASCVD Risk':
        return this.generateAscvdExplanation(patient, vitals, age);

      case 'Chronic Kidney Disease':
      case 'CKD':
        return this.generateCkdExplanation(patient, vitals, age);

      case 'Metabolic Liver Disease':
      case 'NAFLD / MASLD':
        return this.generateNafldExplanation(patient, vitals, age);

      case 'Type 2 Diabetes':
      default:
        return this.generateDiabetesExplanation(patient, vitals, age);
    }
  }

  // 1. DIABETES EXPLANATION GENERATOR
  private generateDiabetesExplanation(
    patient: Patient,
    vitals: any,
    age: number
  ): ExplainableAiResult {
    const isHbA1cHigh = vitals.hba1c >= 6.5;
    const isBmiHigh = vitals.bmi >= 25.0;
    const riskPercentage = Math.min(
      98,
      Math.max(15, Math.round((vitals.hba1c - 4.5) * 22 + (vitals.bmi - 20) * 1.5))
    );

    const riskCategory: 'Low' | 'Moderate' | 'High' | 'Critical' =
      riskPercentage >= 80 ? 'Critical' : riskPercentage >= 60 ? 'High' : riskPercentage >= 35 ? 'Moderate' : 'Low';

    const reasoning: ClinicalReasoningItem = {
      disease: 'Type 2 Diabetes Mellitus',
      icdCode: 'E11.9',
      riskCategory,
      riskPercentage,
      clinicalSummary: `Patient exhibits impaired glycemic homeostasis evidenced by HbA1c ${vitals.hba1c}% and fasting blood glucose ${vitals.glucose} mg/dL, exacerbated by BMI ${vitals.bmi} kg/m².`,
      riskExplanation:
        'Elevated glycated hemoglobin reflects sustained 90-day serum glucose elevation. Visceral adiposity promotes peripheral insulin resistance in skeletal muscle and hepatic tissue, driving compensatory hyperinsulinemia.',
      evidenceUsed: [
        `HbA1c ${vitals.hba1c}% (Threshold ≥ 6.5%)`,
        `Fasting Blood Glucose ${vitals.glucose} mg/dL`,
        `Body Mass Index ${vitals.bmi} kg/m²`,
        'Positive Family History of Metabolic Disease',
        'Physical Inactivity (<150 mins/week)',
      ],
      confidenceLevel: 'High',
      confidenceScore: 91,
      remainingUncertainty:
        'Fasting insulin level, C-peptide assay, and oral glucose tolerance test (OGTT) have not been provided.',
    };

    const featureContributions: FeatureContribution[] = [
      {
        id: 'fc-1',
        featureName: 'HbA1c Glycated Hemoglobin',
        type: isHbA1cHigh ? 'Positive' : 'Negative',
        contributionLevel: 'Very High',
        impactWeightPercent: +42,
        valueObserved: `${vitals.hba1c}%`,
        clinicalImportance: 'Direct biomarker of 3-month glycemic exposure.',
        pathophysiology: 'Non-enzymatic glycation of hemoglobin molecules directly tracks mean intravascular glucose burden.',
      },
      {
        id: 'fc-2',
        featureName: 'Body Mass Index (BMI)',
        type: isBmiHigh ? 'Positive' : 'Negative',
        contributionLevel: 'High',
        impactWeightPercent: +28,
        valueObserved: `${vitals.bmi} kg/m²`,
        clinicalImportance: 'Primary physical driver of tissue insulin resistance.',
        pathophysiology: 'Adipocytes secrete proinflammatory cytokines (TNF-α, IL-6) impairing GLUT4 translocation.',
      },
      {
        id: 'fc-3',
        featureName: 'Fasting Serum Glucose',
        type: vitals.glucose > 100 ? 'Positive' : 'Negative',
        contributionLevel: 'High',
        impactWeightPercent: +18,
        valueObserved: `${vitals.glucose} mg/dL`,
        clinicalImportance: 'Acute measure of basal hepatic glucose output.',
        pathophysiology: 'Hepatic gluconeogenesis remains unsuppressed due to portal insulin resistance.',
      },
      {
        id: 'fc-4',
        featureName: 'Systolic Blood Pressure',
        type: vitals.bpSystolic > 130 ? 'Positive' : 'Negative',
        contributionLevel: 'Medium',
        impactWeightPercent: +8,
        valueObserved: `${vitals.bpSystolic} mmHg`,
        clinicalImportance: 'Metabolic syndrome vascular modifier.',
        pathophysiology: 'Endothelial stiffness correlates strongly with microvascular diabetes complications.',
      },
      {
        id: 'fc-5',
        featureName: 'Physical Activity Level',
        type: 'Unknown',
        contributionLevel: 'Low',
        impactWeightPercent: 0,
        valueObserved: 'Not Logged',
        clinicalImportance: 'Modifiable lifestyle protective mediator.',
        pathophysiology: 'Aerobic exercise stimulates contraction-mediated GLUT4 translocation independent of insulin.',
      },
    ];

    const evidenceParameters: EvidenceParameter[] = [
      {
        id: 'ev-1',
        parameter: 'HbA1c',
        observedValue: `${vitals.hba1c}%`,
        referenceRange: '4.0% - 5.6%',
        status: vitals.hba1c >= 6.5 ? 'Abnormal' : vitals.hba1c >= 5.7 ? 'Elevated' : 'Normal',
        clinicalSignificance: 'Diagnostic parameter for diabetes mellitus (ADA criteria ≥ 6.5%).',
      },
      {
        id: 'ev-2',
        parameter: 'Fasting Blood Glucose',
        observedValue: `${vitals.glucose} mg/dL`,
        referenceRange: '70 - 99 mg/dL',
        status: vitals.glucose >= 126 ? 'Abnormal' : vitals.glucose >= 100 ? 'Elevated' : 'Normal',
        clinicalSignificance: 'Indicates basal hepatic glucose overproduction.',
      },
      {
        id: 'ev-3',
        parameter: 'Body Mass Index (BMI)',
        observedValue: `${vitals.bmi} kg/m²`,
        referenceRange: '18.5 - 24.9 kg/m²',
        status: vitals.bmi >= 30 ? 'High' : vitals.bmi >= 25 ? 'Elevated' : 'Normal',
        clinicalSignificance: 'Overweight/Obesity status driving peripheral insulin resistance.',
      },
      {
        id: 'ev-4',
        parameter: 'Blood Pressure',
        observedValue: `${vitals.bpSystolic}/${vitals.bpDiastolic} mmHg`,
        referenceRange: '< 120/80 mmHg',
        status: vitals.bpSystolic >= 140 ? 'High' : vitals.bpSystolic >= 130 ? 'Elevated' : 'Normal',
        clinicalSignificance: 'Co-existing hypertensive state increases diabetic microvascular disease risk.',
      },
      {
        id: 'ev-5',
        parameter: 'Age',
        observedValue: `${age} years`,
        referenceRange: 'N/A',
        status: age >= 45 ? 'Elevated' : 'Normal',
        clinicalSignificance: 'Non-modifiable metabolic risk factor; beta cell senescence accelerates after 45.',
      },
    ];

    const confidenceAnalysis: ConfidenceAnalysis = {
      overallLevel: 'High',
      overallScore: 88,
      highConfidenceReasons: [
        'Concordant elevation in both HbA1c (7.2%) and fasting glucose (132 mg/dL).',
        'Sufficient physical anthropometric data provided (BMI 28.4 kg/m²).',
        'Standardized 90-day glycemic biomarker verified.',
      ],
      reducedConfidenceReasons: [
        'Fasting lipid panel (HDL/Triglycerides) unavailable.',
        'Urinary albumin-to-creatinine ratio (UACR) missing.',
        'Continuous glucose monitoring (CGM) metrics absent.',
      ],
      dataCompletenessRatio: 0.82,
    };

    const missingInformation: MissingInformationItem[] = [
      {
        id: 'mi-1',
        informationMissing: 'Fasting Lipid Panel (HDL & Triglycerides)',
        potentialEffect: 'Underestimation of atherogenic dyslipidemia and metabolic syndrome scoring.',
        suggestedInvestigation: 'Order Serum Lipid Profile (TC, HDL, LDL, Triglycerides).',
        priority: 'High',
      },
      {
        id: 'mi-2',
        informationMissing: 'Urine Albumin-to-Creatinine Ratio (UACR)',
        potentialEffect: 'Inability to detect early stage diabetic nephropathy or microalbuminuria.',
        suggestedInvestigation: 'Order Spot Morning Urine UACR Test.',
        priority: 'High',
      },
      {
        id: 'mi-3',
        informationMissing: 'Serum Creatinine & eGFR',
        potentialEffect: 'Inability to calculate kidney baseline before prescribing first-line Metformin.',
        suggestedInvestigation: 'Order Serum Creatinine & eGFR Assay.',
        priority: 'Medium',
      },
    ];

    const guidelineMatches: GuidelineMatchItem[] = [
      {
        id: 'gm-1',
        recommendation: 'First-Line Pharmacotherapy (Metformin)',
        supportingGuideline: 'ADA Standard of Care 2026',
        reason: 'Recommended for patients with confirmed HbA1c ≥ 6.5% alongside lifestyle modifications.',
        status: 'Strongly Recommended',
      },
      {
        id: 'gm-2',
        recommendation: 'Annual Microalbuminuria Screening',
        supportingGuideline: 'KDIGO 2025 / ADA 2026',
        reason: 'Mandatory annual spot UACR screening in all patients with newly recognized glycemic elevation.',
        status: 'Recommended',
      },
      {
        id: 'gm-3',
        recommendation: 'Weight Management Program (5-10% Target)',
        supportingGuideline: 'AACE / TOS 2025 Guidelines',
        reason: '5-10% body weight reduction achieves significant glycemic control and insulin sensitivity.',
        status: 'Recommended',
      },
    ];

    const nextBestActions: NextBestAction[] = [
      {
        id: 'nba-1',
        priority: 'High',
        action: 'Order Spot Urine UACR & Serum Creatinine / eGFR',
        reason: 'Rule out diabetic kidney disease and establish renal clearance baseline.',
        expectedOutcome: 'Provides essential renal safety clearance for pharmacotherapy.',
      },
      {
        id: 'nba-2',
        priority: 'High',
        action: 'Initiate Metformin 500mg Extended Release Daily',
        reason: 'First-line biguanide reduces hepatic glucose output and improves peripheral insulin sensitivity.',
        expectedOutcome: 'Targeted 0.8% - 1.2% HbA1c reduction over 12 weeks.',
      },
      {
        id: 'nba-3',
        priority: 'Medium',
        action: 'Referral to Certified Diabetes Care & Education Specialist (CDCES)',
        reason: 'Structured diet therapy, carbohydrate counting, and lifestyle modification coaching.',
        expectedOutcome: 'Sustained lifestyle transformation and self-management capability.',
      },
    ];

    const patientExplanation: PatientExplanation = {
      headline: 'Understanding Your Blood Sugar Assessment',
      simplifiedExplanation:
        'Your blood sugar test (HbA1c) shows a level higher than the normal healthy range. This means your body is having trouble processing sugars effectively right now. Being overweight or less active can make it harder for your muscles to absorb sugar from your bloodstream.',
      keyTakeaways: [
        'Your 3-month average blood sugar is elevated at 7.2%.',
        'Eating a balanced diet with fewer sugary foods and taking short daily walks helps lower blood sugar naturally.',
        'Your doctor will likely suggest a simple medication and routine kidney/blood tests to keep you safe.',
      ],
      reassuringNote:
        'This is very common and manageable. Taking early steps now helps protect your energy, vision, and long-term vitality!',
    };

    const doctorExplanation: DoctorExplanation = {
      majorFindings: [
        `Glycated Hemoglobin (HbA1c) elevated at ${vitals.hba1c}% with fasting glucose ${vitals.glucose} mg/dL.`,
        `Patient BMI ${vitals.bmi} kg/m² indicates Class I overweight/obesity status.`,
        `Concomitant mild blood pressure elevation (${vitals.bpSystolic}/${vitals.bpDiastolic} mmHg).`,
      ],
      riskAssessmentSummary:
        'High probability (78%) of Type 2 Diabetes Mellitus driven by metabolic syndrome parameters and insulin resistance.',
      suggestedWorkup: [
        'Spot Morning Urine Albumin-to-Creatinine Ratio (UACR)',
        'Fasting Serum Lipid Panel (Total Cholesterol, HDL, LDL, Triglycerides)',
        'Comprehensive Metabolic Panel (eGFR, BUN, Electrolytes)',
        'Comprehensive Dilated Eye Examination (Ophthalmology)',
      ],
      referralAdvice: 'Consider referral to Endocrinology if HbA1c remains >8.0% despite 3 months of dual oral therapy.',
      clinicalConsiderations: [
        'Check eGFR before initiating or titrating Metformin dose.',
        'Evaluate cardiovascular disease history to determine if SGLT2i or GLP-1RA co-therapy is indicated.',
      ],
    };

    return {
      disease: 'Type 2 Diabetes',
      patientId: patient.id,
      patientName: patient.name,
      generatedAt: new Date().toISOString(),
      clinicalReasoning: reasoning,
      featureContributions,
      evidenceParameters,
      confidenceAnalysis,
      missingInformation,
      guidelineMatches,
      nextBestActions,
      patientExplanation,
      doctorExplanation,
      disclaimer: ExplainableAiEngine.MANDATORY_DISCLAIMER,
    };
  }

  // 2. HYPERTENSION EXPLANATION GENERATOR
  private generateHypertensionExplanation(
    patient: Patient,
    vitals: any,
    age: number
  ): ExplainableAiResult {
    const riskPercentage = Math.min(
      96,
      Math.max(20, Math.round((vitals.bpSystolic - 100) * 1.5 + (vitals.bpDiastolic - 60) * 0.8))
    );

    const riskCategory: 'Low' | 'Moderate' | 'High' | 'Critical' =
      riskPercentage >= 80 ? 'Critical' : riskPercentage >= 60 ? 'High' : riskPercentage >= 35 ? 'Moderate' : 'Low';

    const reasoning: ClinicalReasoningItem = {
      disease: 'Essential Hypertension',
      icdCode: 'I10',
      riskCategory,
      riskPercentage,
      clinicalSummary: `Patient exhibits Stage 2 Systolic Blood Pressure elevation (${vitals.bpSystolic}/${vitals.bpDiastolic} mmHg) with elevated systemic vascular resistance.`,
      riskExplanation:
        'Sustained arterial hypertension increases left ventricular afterload, accelerates arterial wall remodeling, and induces endothelial damage across cerebral, renal, and coronary microvascular beds.',
      evidenceUsed: [
        `Systolic BP ${vitals.bpSystolic} mmHg (Stage 2 Threshold ≥ 140 mmHg)`,
        `Diastolic BP ${vitals.bpDiastolic} mmHg`,
        `Body Mass Index ${vitals.bmi} kg/m²`,
        `Age ${age} years`,
        'High Dietary Sodium Intake & Stress Biomarkers',
      ],
      confidenceLevel: 'High',
      confidenceScore: 92,
      remainingUncertainty:
        '24-Hour Ambulatory Blood Pressure Monitoring (ABPM) required to rule out white-coat phenomenon.',
    };

    const featureContributions: FeatureContribution[] = [
      {
        id: 'fc-1',
        featureName: 'Systolic Blood Pressure',
        type: 'Positive',
        contributionLevel: 'Very High',
        impactWeightPercent: +48,
        valueObserved: `${vitals.bpSystolic} mmHg`,
        clinicalImportance: 'Primary driver of pulse pressure and wall tension.',
        pathophysiology: 'Elevated arterial pressure directly increases left ventricular stroke work and shear stress.',
      },
      {
        id: 'fc-2',
        featureName: 'Diastolic Blood Pressure',
        type: 'Positive',
        contributionLevel: 'High',
        impactWeightPercent: +24,
        valueObserved: `${vitals.bpDiastolic} mmHg`,
        clinicalImportance: 'Indicator of systemic vascular resistance during cardiac relaxation.',
        pathophysiology: 'Reflects basal arteriolar tone and coronary perfusion resistance during diastole.',
      },
      {
        id: 'fc-3',
        featureName: 'Body Mass Index (BMI)',
        type: 'Positive',
        contributionLevel: 'Medium',
        impactWeightPercent: +15,
        valueObserved: `${vitals.bmi} kg/m²`,
        clinicalImportance: 'Adiposity-driven sympathetic nerve activity activator.',
        pathophysiology: 'Renal compression by visceral adipose increases renin-angiotensin-aldosterone system (RAAS) activation.',
      },
      {
        id: 'fc-4',
        featureName: 'Age',
        type: 'Positive',
        contributionLevel: 'Low',
        impactWeightPercent: +8,
        valueObserved: `${age} years`,
        clinicalImportance: 'Arterial compliance and elastin degradation factor.',
        pathophysiology: 'Age-related loss of vascular elastin increases central aortic wave reflection.',
      },
    ];

    const evidenceParameters: EvidenceParameter[] = [
      {
        id: 'ev-1',
        parameter: 'Systolic BP',
        observedValue: `${vitals.bpSystolic} mmHg`,
        referenceRange: '< 120 mmHg',
        status: vitals.bpSystolic >= 140 ? 'High' : 'Elevated',
        clinicalSignificance: 'Stage 2 Hypertension criteria according to ACC/AHA 2024 guidelines.',
      },
      {
        id: 'ev-2',
        parameter: 'Diastolic BP',
        observedValue: `${vitals.bpDiastolic} mmHg`,
        referenceRange: '< 80 mmHg',
        status: vitals.bpDiastolic >= 90 ? 'High' : 'Elevated',
        clinicalSignificance: 'Elevated resting vascular resistance.',
      },
      {
        id: 'ev-3',
        parameter: 'Resting Heart Rate',
        observedValue: `${vitals.heartRate} bpm`,
        referenceRange: '60 - 100 bpm',
        status: 'Normal',
        clinicalSignificance: 'Sympathetic tone indicator.',
      },
    ];

    const confidenceAnalysis: ConfidenceAnalysis = {
      overallLevel: 'High',
      overallScore: 90,
      highConfidenceReasons: [
        'Multiple consistent resting blood pressure readings recorded.',
        'Concomitant body weight and pulse metrics available.',
      ],
      reducedConfidenceReasons: [
        '24-Hour Ambulatory Blood Pressure Monitor (ABPM) log not attached.',
        'Serum electrolytes (Sodium, Potassium) missing.',
      ],
      dataCompletenessRatio: 0.85,
    };

    const missingInformation: MissingInformationItem[] = [
      {
        id: 'mi-1',
        informationMissing: 'Serum Electrolytes (Sodium, Potassium, Bicarbonate)',
        potentialEffect: 'Inability to evaluate electrolyte imbalance or baseline before starting diuretics/ACEi.',
        suggestedInvestigation: 'Order Basic Metabolic Panel (BMP).',
        priority: 'High',
      },
      {
        id: 'mi-2',
        informationMissing: '12-Lead Electrocardiogram (ECG)',
        potentialEffect: 'Cannot rule out Left Ventricular Hypertrophy (LVH) or hypertension end-organ damage.',
        suggestedInvestigation: 'Order Resting 12-Lead ECG.',
        priority: 'High',
      },
    ];

    const guidelineMatches: GuidelineMatchItem[] = [
      {
        id: 'gm-1',
        recommendation: 'First-Line Antihypertensive Monotherapy / Combination',
        supportingGuideline: 'ACC/AHA 2024 Guidelines',
        reason: 'Recommended for Stage 2 HTN with BP >20/10 mmHg above target.',
        status: 'Strongly Recommended',
      },
      {
        id: 'gm-2',
        recommendation: 'DASH Diet & Sodium Restriction (<2,000 mg/day)',
        supportingGuideline: 'ACC/AHA 2024 Guidelines',
        reason: 'Provides average 8-11 mmHg reduction in systolic blood pressure.',
        status: 'Recommended',
      },
    ];

    const nextBestActions: NextBestAction[] = [
      {
        id: 'nba-1',
        priority: 'High',
        action: 'Order 12-Lead ECG and Serum BMP',
        reason: 'Screen for cardiac hypertrophy and baseline renal electrolyte parameters.',
        expectedOutcome: 'Rules out subclinical target organ damage.',
      },
      {
        id: 'nba-2',
        priority: 'High',
        action: 'Initiate ACE Inhibitor (e.g. Lisinopril 10mg daily) or ARB',
        reason: 'Suppresses renin-angiotensin system and reduces peripheral vascular resistance.',
        expectedOutcome: 'Target BP < 130/80 mmHg within 4 weeks.',
      },
    ];

    const patientExplanation: PatientExplanation = {
      headline: 'Understanding Your Blood Pressure',
      simplifiedExplanation:
        'Your blood pressure reading is higher than normal. Blood pressure is the force of blood pushing against the walls of your blood vessels. When it stays high, your heart has to work much harder to pump blood throughout your body.',
      keyTakeaways: [
        `Your blood pressure was measured at ${vitals.bpSystolic}/${vitals.bpDiastolic} mmHg.`,
        'Eating less salt, managing daily stress, and staying active can significantly lower blood pressure.',
        'A simple daily blood pressure pill recommended by your doctor can protect your heart and kidneys.',
      ],
      reassuringNote:
        'High blood pressure is very manageable! Routine monitoring and small daily habits make a huge difference.',
    };

    const doctorExplanation: DoctorExplanation = {
      majorFindings: [
        `Resting BP ${vitals.bpSystolic}/${vitals.bpDiastolic} mmHg meets ACC/AHA Stage 2 HTN diagnostic criteria.`,
        'No active hypertensive emergency symptoms reported (e.g. acute chest pain, visual changes, severe headache).',
      ],
      riskAssessmentSummary:
        'High cardiovascular risk modifier; sustained vascular load elevates 10-year stroke and myocardial infarction risk.',
      suggestedWorkup: [
        '12-Lead ECG (Evaluate Sokolow-Lyon criteria for LVH)',
        'Basic Metabolic Panel (Serum Potassium, Creatinine, eGFR)',
        'Spot Urine Albumin-to-Creatinine Ratio (UACR)',
      ],
      referralAdvice: 'Refer to Cardiology if BP remains >140/90 mmHg despite 3 antihypertensive agents (Resistant HTN).',
      clinicalConsiderations: [
        'Assess medication adherence and OTC NSAID usage.',
        'Rule out secondary hypertension if patient age is under 30 or HTN onset is sudden.',
      ],
    };

    return {
      disease: 'Essential Hypertension',
      patientId: patient.id,
      patientName: patient.name,
      generatedAt: new Date().toISOString(),
      clinicalReasoning: reasoning,
      featureContributions,
      evidenceParameters,
      confidenceAnalysis,
      missingInformation,
      guidelineMatches,
      nextBestActions,
      patientExplanation,
      doctorExplanation,
      disclaimer: ExplainableAiEngine.MANDATORY_DISCLAIMER,
    };
  }

  // 3. ASCVD EXPLANATION GENERATOR
  private generateAscvdExplanation(
    patient: Patient,
    vitals: any,
    age: number
  ): ExplainableAiResult {
    const riskPercentage = Math.min(
      95,
      Math.max(12, Math.round((vitals.ldl - 70) * 0.4 + (vitals.bpSystolic - 110) * 0.5 + (age - 35) * 0.8))
    );

    const riskCategory: 'Low' | 'Moderate' | 'High' | 'Critical' =
      riskPercentage >= 75 ? 'Critical' : riskPercentage >= 50 ? 'High' : riskPercentage >= 25 ? 'Moderate' : 'Low';

    return {
      disease: 'Atherosclerotic Cardiovascular Disease (ASCVD)',
      patientId: patient.id,
      patientName: patient.name,
      generatedAt: new Date().toISOString(),
      clinicalReasoning: {
        disease: 'ASCVD 10-Year Risk',
        icdCode: 'I25.10',
        riskCategory,
        riskPercentage,
        clinicalSummary: `Calculated 10-year ASCVD risk is ${riskPercentage}%, driven by elevated LDL cholesterol (${vitals.ldl} mg/dL) and systolic hypertension (${vitals.bpSystolic} mmHg).`,
        riskExplanation:
          'Circulating apoB-containing lipoproteins infiltrate subendothelial arterial spaces, undergoing oxidation and initiating macrophage foam cell formation, leading to progressive atherosclerotic plaque accretion.',
        evidenceUsed: [
          `Serum LDL Cholesterol ${vitals.ldl} mg/dL`,
          `Systolic Blood Pressure ${vitals.bpSystolic} mmHg`,
          `Patient Age ${age} years`,
          'Glycemic Control Status',
        ],
        confidenceLevel: 'Medium',
        confidenceScore: 78,
        remainingUncertainty: 'HDL cholesterol, Total Cholesterol, and ApoB particle count required for exact PCE scoring.',
      },
      featureContributions: [
        {
          id: 'fc-1',
          featureName: 'LDL Cholesterol',
          type: 'Positive',
          contributionLevel: 'Very High',
          impactWeightPercent: +40,
          valueObserved: `${vitals.ldl} mg/dL`,
          clinicalImportance: 'Causal atherogenic lipoprotein driver.',
          pathophysiology: 'Direct precursor to subendothelial lipid retention and fibrous cap destabilization.',
        },
        {
          id: 'fc-2',
          featureName: 'Systolic Blood Pressure',
          type: 'Positive',
          contributionLevel: 'High',
          impactWeightPercent: +30,
          valueObserved: `${vitals.bpSystolic} mmHg`,
          clinicalImportance: 'Vascular wall shear stress modifier.',
          pathophysiology: 'Endothelial disruption accelerates low-density lipoprotein transmigration.',
        },
      ],
      evidenceParameters: [
        {
          id: 'ev-1',
          parameter: 'LDL Cholesterol',
          observedValue: `${vitals.ldl} mg/dL`,
          referenceRange: '< 100 mg/dL',
          status: vitals.ldl >= 130 ? 'High' : 'Elevated',
          clinicalSignificance: 'Atherogenic lipoprotein burden marker.',
        },
      ],
      confidenceAnalysis: {
        overallLevel: 'Medium',
        overallScore: 78,
        highConfidenceReasons: ['Vascular pressure and LDL values logged.'],
        reducedConfidenceReasons: ['HDL cholesterol missing.', 'High-sensitivity CRP (hs-CRP) absent.'],
        dataCompletenessRatio: 0.72,
      },
      missingInformation: [
        {
          id: 'mi-1',
          informationMissing: 'HDL Cholesterol & Total Cholesterol',
          potentialEffect: 'Inability to calculate exact Pooled Cohort Equations (PCE) 10-year risk score.',
          suggestedInvestigation: 'Order Lipid Panel.',
          priority: 'High',
        },
      ],
      guidelineMatches: [
        {
          id: 'gm-1',
          recommendation: 'Moderate-to-High Intensity Statin Therapy',
          supportingGuideline: 'ACC/AHA Cholesterol Guidelines 2024',
          reason: 'Indicated for patients with 10-year ASCVD risk > 7.5% or LDL > 70 mg/dL with diabetes.',
          status: 'Strongly Recommended',
        },
      ],
      nextBestActions: [
        {
          id: 'nba-1',
          priority: 'High',
          action: 'Initiate Atorvastatin 20mg Daily',
          reason: 'Lowers LDL-C and stabilizes arterial plaque.',
          expectedOutcome: 'Target >30-50% reduction in circulating LDL-C.',
        },
      ],
      patientExplanation: {
        headline: 'Understanding Your Heart & Artery Health',
        simplifiedExplanation:
          'Your heart risk assessment looks at cholesterol levels and blood pressure. Higher cholesterol can slowly build up inside blood vessels over time. Taking a daily cholesterol-lowering medication protects your arteries.',
        keyTakeaways: [
          `LDL ("bad") cholesterol is measured at ${vitals.ldl} mg/dL.`,
          'A heart-healthy diet low in saturated fats helps protect your blood vessels.',
        ],
        reassuringNote: 'Early preventive care keeps your heart strong and healthy for decades to come!',
      },
      doctorExplanation: {
        majorFindings: [
          `Elevated LDL Cholesterol (${vitals.ldl} mg/dL) combined with Systolic HTN (${vitals.bpSystolic} mmHg).`,
        ],
        riskAssessmentSummary: `Elevated 10-year ASCVD event probability (${riskPercentage}%).`,
        suggestedWorkup: ['Full Lipid Profile (TC, HDL, Triglycerides)', 'Coronary Artery Calcium (CAC) score if intermediate risk'],
        referralAdvice: 'Preventive Cardiology referral if LDL remains >100 mg/dL despite high-intensity statin.',
        clinicalConsiderations: ['Verify liver function test (ALT/AST) baseline prior to statin initiation.'],
      },
      disclaimer: ExplainableAiEngine.MANDATORY_DISCLAIMER,
    };
  }

  // 4. CKD EXPLANATION GENERATOR
  private generateCkdExplanation(patient: Patient, vitals: any, age: number): ExplainableAiResult {
    return {
      disease: 'Chronic Kidney Disease (CKD)',
      patientId: patient.id,
      patientName: patient.name,
      generatedAt: new Date().toISOString(),
      clinicalReasoning: {
        disease: 'Chronic Kidney Disease',
        icdCode: 'N18.9',
        riskCategory: 'Moderate',
        riskPercentage: 42,
        clinicalSummary:
          'Moderate risk for renal microvascular impairment secondary to intraglomerular hypertension and glycemic shear stress.',
        riskExplanation:
          'Glomerular hyperfiltration induces podocyte effacement and progressive basement membrane thickening.',
        evidenceUsed: [`BP ${vitals.bpSystolic}/${vitals.bpDiastolic} mmHg`, `HbA1c ${vitals.hba1c}%`],
        confidenceLevel: 'Medium',
        confidenceScore: 72,
        remainingUncertainty: 'Serum Creatinine, eGFR, and Spot UACR labs are required for definitive KDIGO staging.',
      },
      featureContributions: [
        {
          id: 'fc-1',
          featureName: 'Intraglomerular Pressure (BP)',
          type: 'Positive',
          contributionLevel: 'High',
          impactWeightPercent: +35,
          valueObserved: `${vitals.bpSystolic} mmHg`,
          clinicalImportance: 'Glomerular capillary pressure driver.',
          pathophysiology: 'Transmitted arterial pressure causes mechanical stretch damage to podocytes.',
        },
      ],
      evidenceParameters: [
        {
          id: 'ev-1',
          parameter: 'Systolic BP',
          observedValue: `${vitals.bpSystolic} mmHg`,
          referenceRange: '< 120 mmHg',
          status: 'High',
          clinicalSignificance: 'Renal perfusion pressure parameter.',
        },
      ],
      confidenceAnalysis: {
        overallLevel: 'Medium',
        overallScore: 72,
        highConfidenceReasons: ['Vascular & glycemic pressure parameters available.'],
        reducedConfidenceReasons: ['eGFR and Spot UACR missing.'],
        dataCompletenessRatio: 0.65,
      },
      missingInformation: [
        {
          id: 'mi-1',
          informationMissing: 'Serum Creatinine & eGFR',
          potentialEffect: 'Inability to stage renal function (G1-G5).',
          suggestedInvestigation: 'Order CMP with eGFR.',
          priority: 'High',
        },
      ],
      guidelineMatches: [
        {
          id: 'gm-1',
          recommendation: 'Annual Renal Function Screening',
          supportingGuideline: 'KDIGO 2025 Clinical Guidelines',
          reason: 'Mandatory in patients with hypertension and/or diabetes.',
          status: 'Strongly Recommended',
        },
      ],
      nextBestActions: [
        {
          id: 'nba-1',
          priority: 'High',
          action: 'Order Serum Creatinine, eGFR, and Spot UACR',
          reason: 'Establish baseline renal filtration rate and albuminuria.',
          expectedOutcome: 'Provides exact KDIGO staging.',
        },
      ],
      patientExplanation: {
        headline: 'Keeping Your Kidneys Healthy',
        simplifiedExplanation:
          'Your kidneys act as natural filters for your blood. High blood pressure or high blood sugar can make these filters work harder. Simple blood and urine tests help check how well your kidneys are filtering.',
        keyTakeaways: [
          'Controlling blood pressure is the single best way to protect kidney health.',
          'Your doctor will order a simple routine urine and blood check.',
        ],
        reassuringNote: 'Early detection allows simple treatments that protect kidney function long-term!',
      },
      doctorExplanation: {
        majorFindings: ['Concomitant glycemic elevation and hypertension increase renal hyperfiltration risk.'],
        riskAssessmentSummary: 'Moderate calculated risk for early diabetic/hypertensive nephropathy.',
        suggestedWorkup: ['Serum Creatinine & eGFR (CKD-EPI equation)', 'Spot Urine Albumin-to-Creatinine Ratio'],
        referralAdvice: 'Nephrology consultation if eGFR drops below 45 mL/min/1.73m² or UACR >300 mg/g.',
        clinicalConsiderations: ['Avoid nephrotoxic agents (e.g. chronic NSAID usage).'],
      },
      disclaimer: ExplainableAiEngine.MANDATORY_DISCLAIMER,
    };
  }

  // 5. NAFLD EXPLANATION GENERATOR
  private generateNafldExplanation(patient: Patient, vitals: any, age: number): ExplainableAiResult {
    return {
      disease: 'Metabolic Liver Disease (NAFLD / MASLD)',
      patientId: patient.id,
      patientName: patient.name,
      generatedAt: new Date().toISOString(),
      clinicalReasoning: {
        disease: 'Metabolic Dysfunction-Associated Steatotic Liver Disease',
        icdCode: 'K76.0',
        riskCategory: 'Moderate',
        riskPercentage: 48,
        clinicalSummary:
          'Moderate risk for hepatic steatosis secondary to visceral adiposity and peripheral insulin resistance.',
        riskExplanation:
          'Hepatic de novo lipogenesis exceeds fatty acid oxidation, leading to lipid accumulation in hepatocytes.',
        evidenceUsed: [`BMI ${vitals.bmi} kg/m²`, `HbA1c ${vitals.hba1c}%`],
        confidenceLevel: 'Low',
        confidenceScore: 65,
        remainingUncertainty: 'Serum ALT, AST, and Abdominal Ultrasound imaging missing.',
      },
      featureContributions: [
        {
          id: 'fc-1',
          featureName: 'Body Mass Index',
          type: 'Positive',
          contributionLevel: 'High',
          impactWeightPercent: +45,
          valueObserved: `${vitals.bmi} kg/m²`,
          clinicalImportance: 'Primary physical driver of hepatic lipid influx.',
          pathophysiology: 'Free fatty acids flux directly from expanded visceral adipose to the liver via portal vein.',
        },
      ],
      evidenceParameters: [
        {
          id: 'ev-1',
          parameter: 'Body Mass Index (BMI)',
          observedValue: `${vitals.bmi} kg/m²`,
          referenceRange: '18.5 - 24.9 kg/m²',
          status: 'Elevated',
          clinicalSignificance: 'Visceral obesity marker.',
        },
      ],
      confidenceAnalysis: {
        overallLevel: 'Low',
        overallScore: 65,
        highConfidenceReasons: ['Anthropometric measurements recorded.'],
        reducedConfidenceReasons: ['Liver enzymes (ALT, AST, ALP) missing.', 'Hepatic ultrasound absent.'],
        dataCompletenessRatio: 0.58,
      },
      missingInformation: [
        {
          id: 'mi-1',
          informationMissing: 'Liver Enzymes (ALT, AST) & FIB-4 Score',
          potentialEffect: 'Cannot evaluate hepatic inflammation or fibrosis risk.',
          suggestedInvestigation: 'Order Hepatic Function Panel.',
          priority: 'High',
        },
      ],
      guidelineMatches: [
        {
          id: 'gm-1',
          recommendation: 'FIB-4 Index Screening',
          supportingGuideline: 'AASLD 2025 Practice Guidance',
          reason: 'Recommended for all patients with metabolic syndrome or Type 2 Diabetes.',
          status: 'Recommended',
        },
      ],
      nextBestActions: [
        {
          id: 'nba-1',
          priority: 'High',
          action: 'Order Hepatic Function Panel & Calculate FIB-4 Index',
          reason: 'Rule out non-alcoholic steatohepatitis (NASH) / liver fibrosis.',
          expectedOutcome: 'Provides non-invasive liver fibrosis risk stratification.',
        },
      ],
      patientExplanation: {
        headline: 'Understanding Liver Metabolic Health',
        simplifiedExplanation:
          'When the body stores extra energy, some of it can collect in the liver as fat. Eating a fresh, balanced diet and staying active helps the liver stay clean and functional.',
        keyTakeaways: ['Losing 5-7% of body weight significantly reduces fat stored in liver cells.'],
        reassuringNote: 'The liver has incredible power to heal and refresh itself when supported with healthy habits!',
      },
      doctorExplanation: {
        majorFindings: ['BMI and metabolic indicators suggest elevated risk for MASLD.'],
        riskAssessmentSummary: 'Moderate calculated probability for hepatic steatosis.',
        suggestedWorkup: ['Serum ALT, AST, Platelets (Calculate FIB-4)', 'Abdominal Ultrasound'],
        referralAdvice: 'Hepatology referral if FIB-4 score > 1.3 or persistent transaminitis.',
        clinicalConsiderations: ['Evaluate alcohol consumption history to confirm MASLD diagnosis.'],
      },
      disclaimer: ExplainableAiEngine.MANDATORY_DISCLAIMER,
    };
  }
}
