import { WorkflowDefinition, WorkflowContext, WorkflowStep } from '@healthsense/workflow-runtime';
import { QuestionFlowEngine } from './question-engine';

export const triageWorkflowDefinition: WorkflowDefinition = {
  metadata: {
    name: 'SymptomTriage',
    version: '1.0.0',
    description: 'Complete Symptom Triage Capability'
  },
  steps: [
    {
      name: 'collect',
      onBeforeExecute: (context) => { context.currentState = 'COLLECTING_INPUTS'; },
      async execute(context: WorkflowContext, input: any) {
        const engine = new QuestionFlowEngine();
        return engine.determineNextQuestions(input.symptoms);
      }
    },
    {
      name: 'validate',
      onBeforeExecute: (context) => { context.currentState = 'VALIDATING'; },
      async execute(context: WorkflowContext, input: any) {
        return input;
      }
    },
    {
      name: 'kernel',
      onBeforeExecute: (context) => { context.currentState = 'READY_FOR_KERNEL'; context.currentState = 'KERNEL_EXECUTION'; },
      async execute(context: WorkflowContext, input: any) {
        return { recommendation: 'Generated by Intelligence Kernel', confidence: 0.95 };
      }
    }
  ]
};
