export const REFERRAL_THRESHOLDS = {
  DIABETES: {
    HIGH_HBA1C: 8.0,
    CRITICAL_HBA1C: 9.5
  },
  HYPERTENSION: {
    STAGE2_SBP: 140,
    STAGE2_DBP: 90,
    CRISIS_SBP: 168,
    CRISIS_DBP: 100
  },
  CKD: {
    STAGE3A_EGFR: 60,
    STAGE3B_EGFR: 45,
    MICROALBUMINURIA_UACR: 30,
    MACROALBUMINURIA_UACR: 300
  }
} as const;
