export type HUSEEntityType = 
  | 'PATIENT'
  | 'ASSESSMENT'
  | 'CLINICAL_WORKFLOW'
  | 'DECISION'
  | 'MEDICAL_REPORT'
  | 'NOTIFICATION';

export type HUSEStateMap = {
  PATIENT: 'UNVERIFIED' | 'ACTIVE' | 'SUSPENDED' | 'ARCHIVED';
  ASSESSMENT: 'INITIALIZED' | 'IN_PROGRESS' | 'REASONING' | 'COMPLETED' | 'CANCELLED';
  CLINICAL_WORKFLOW: 'CREATED' | 'VALIDATED' | 'RUNNING' | 'WAITING_INPUT' | 'COMPLETED' | 'FAILED';
  DECISION: 'DRAFTED' | 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED';
  MEDICAL_REPORT: 'UPLOADING' | 'STORED' | 'ANALYZED' | 'ARCHIVED';
  NOTIFICATION: 'QUEUED' | 'SENDING' | 'DELIVERED' | 'FAILED';
};

export const HUSE_LIFECYCLE_GRAPHS: Record<HUSEEntityType, Record<string, string[]>> = {
  PATIENT: {
    UNVERIFIED: ['ACTIVE', 'ARCHIVED'],
    ACTIVE: ['SUSPENDED', 'ARCHIVED'],
    SUSPENDED: ['ACTIVE', 'ARCHIVED'],
    ARCHIVED: []
  },
  ASSESSMENT: {
    INITIALIZED: ['IN_PROGRESS', 'CANCELLED'],
    IN_PROGRESS: ['REASONING', 'CANCELLED'],
    REASONING: ['COMPLETED', 'CANCELLED', 'FAILED'],
    COMPLETED: [],
    CANCELLED: []
  },
  CLINICAL_WORKFLOW: {
    CREATED: ['VALIDATED', 'FAILED'],
    VALIDATED: ['RUNNING', 'FAILED'],
    RUNNING: ['WAITING_INPUT', 'COMPLETED', 'FAILED'],
    WAITING_INPUT: ['RUNNING', 'CANCELLED', 'FAILED'],
    COMPLETED: [],
    FAILED: ['CREATED'] // Retry restart
  },
  DECISION: {
    DRAFTED: ['PENDING_REVIEW', 'APPROVED', 'REJECTED'],
    PENDING_REVIEW: ['APPROVED', 'REJECTED'],
    APPROVED: [],
    REJECTED: ['DRAFTED']
  },
  MEDICAL_REPORT: {
    UPLOADING: ['STORED', 'FAILED'],
    STORED: ['ANALYZED', 'ARCHIVED'],
    ANALYZED: ['ARCHIVED'],
    ARCHIVED: []
  },
  NOTIFICATION: {
    QUEUED: ['SENDING', 'FAILED'],
    SENDING: ['DELIVERED', 'FAILED'],
    DELIVERED: [],
    FAILED: ['QUEUED'] // Retry
  }
};
