import { Patient, AssessmentRecord, LabReport, Recommendation } from './types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'p-101',
    mrn: 'MRN-849201',
    name: 'Eleanor Vance',
    age: 58,
    gender: 'Female',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    riskLevel: 'High',
    riskScore: 84,
    primaryDoctor: 'Dr. Arthur Pendelton, MD',
    conditions: ['Type 2 Diabetes (Uncontrolled)', 'Stage 2 Hypertension', 'NAFLD Risk'],
    lastAssessmentDate: '2026-07-28',
    vitals: {
      bpSystolic: 148,
      bpDiastolic: 94,
      heartRate: 82,
      bmi: 31.4,
      glucose: 182,
      hba1c: 8.6,
      ldl: 168,
      weightKg: 84.5,
    },
    pendingReferral: true,
    referralSpecialist: 'Endocrinology & Cardiology',
    recentActivity: [
      {
        id: 'act-1',
        date: '2026-07-28',
        type: 'assessment',
        title: 'Lifestyle Disease Screening Assessment',
        description: 'CDSS identified High Cardiovascular & Diabetes Progression Risk. Referred to Endocrinology.',
        badgeText: 'High Risk Alert',
        badgeType: 'danger',
      },
      {
        id: 'act-2',
        date: '2026-07-25',
        type: 'lab',
        title: 'Comprehensive Metabolic & Lipid Panel Uploaded',
        description: 'HbA1c increased to 8.6%. LDL elevated at 168 mg/dL.',
        badgeText: 'Abnormal Vitals',
        badgeType: 'warning',
      },
      {
        id: 'act-3',
        date: '2026-07-15',
        type: 'vital',
        title: 'Home Blood Pressure Logged',
        description: '150/96 mmHg average morning reading.',
        badgeText: 'Hypertension',
        badgeType: 'warning',
      },
    ],
    medications: [
      {
        id: 'm-1',
        name: 'Metformin XR',
        strength: '1000 mg',
        dosage: '1000mg',
        frequency: 'Twice daily with meals',
        schedule: { morning: true, afternoon: false, night: true },
        timing: 'After Food',
        startDate: '2026-05-10',
        endDate: '2026-11-10',
        duration: '180 Days',
        purpose: 'Glycemic Regulation & Insulin Sensitivity',
        sideEffects: ['Mild stomach discomfort', 'Nausea (transient)'],
        refillReminder: true,
        refillDate: '2026-08-15',
        refillPillsRemaining: 14,
        missedDoseReminder: true,
        reminderTimes: ['08:00 AM', '08:00 PM'],
        takenToday: true,
        takenTimesToday: { morning: true, afternoon: false, night: true },
        historyLogs: [
          { id: 'h-1', date: '2026-08-01', time: '08:15 AM', doseSlot: 'Morning', status: 'taken' },
          { id: 'h-2', date: '2026-07-31', time: '08:00 AM', doseSlot: 'Morning', status: 'taken' },
          { id: 'h-3', date: '2026-07-31', time: '08:20 PM', doseSlot: 'Night', status: 'taken' },
          { id: 'h-4', date: '2026-07-30', time: '08:05 AM', doseSlot: 'Morning', status: 'taken' },
          { id: 'h-5', date: '2026-07-30', time: '08:10 PM', doseSlot: 'Night', status: 'missed' },
        ],
      },
      {
        id: 'm-2',
        name: 'Lisinopril',
        strength: '20 mg',
        dosage: '20mg',
        frequency: 'Once daily (Morning)',
        schedule: { morning: true, afternoon: false, night: false },
        timing: 'After Food',
        startDate: '2026-04-01',
        endDate: '2026-10-01',
        duration: '180 Days',
        purpose: 'Blood Pressure Control & Renoprotection',
        sideEffects: ['Dry cough', 'Mild dizziness'],
        refillReminder: true,
        refillDate: '2026-08-20',
        refillPillsRemaining: 19,
        missedDoseReminder: true,
        reminderTimes: ['08:30 AM'],
        takenToday: true,
        takenTimesToday: { morning: true },
        historyLogs: [
          { id: 'h-6', date: '2026-08-01', time: '08:35 AM', doseSlot: 'Morning', status: 'taken' },
          { id: 'h-7', date: '2026-07-31', time: '08:30 AM', doseSlot: 'Morning', status: 'taken' },
          { id: 'h-8', date: '2026-07-30', time: '08:40 AM', doseSlot: 'Morning', status: 'taken' },
        ],
      },
      {
        id: 'm-3',
        name: 'Atorvastatin',
        strength: '40 mg',
        dosage: '40mg',
        frequency: 'Once daily (Bedtime)',
        schedule: { morning: false, afternoon: false, night: true },
        timing: 'After Food',
        startDate: '2026-06-15',
        endDate: '2026-12-15',
        duration: '180 Days',
        purpose: 'LDL Cholesterol Reduction & ASCVD Prevention',
        sideEffects: ['Muscle stiffness', 'Mild fatigue'],
        refillReminder: false,
        refillDate: '2026-09-10',
        refillPillsRemaining: 40,
        missedDoseReminder: true,
        reminderTimes: ['09:30 PM'],
        takenToday: false,
        takenTimesToday: { night: false },
        historyLogs: [
          { id: 'h-9', date: '2026-07-31', time: '09:40 PM', doseSlot: 'Night', status: 'taken' },
          { id: 'h-10', date: '2026-07-30', time: '09:35 PM', doseSlot: 'Night', status: 'taken' },
        ],
      },
      {
        id: 'm-4',
        name: 'Empagliflozin',
        strength: '10 mg',
        dosage: '10mg',
        frequency: 'Once daily (Morning)',
        schedule: { morning: true, afternoon: false, night: false },
        timing: 'Before Food',
        startDate: '2026-07-01',
        endDate: '2026-12-31',
        duration: '180 Days',
        purpose: 'Cardiorenal Glycemic Protection (SGLT2i)',
        sideEffects: ['Increased urination', 'Thirst'],
        refillReminder: true,
        refillDate: '2026-08-10',
        refillPillsRemaining: 9,
        missedDoseReminder: true,
        reminderTimes: ['07:45 AM'],
        takenToday: true,
        takenTimesToday: { morning: true },
        historyLogs: [
          { id: 'h-11', date: '2026-08-01', time: '07:50 AM', doseSlot: 'Morning', status: 'taken' },
          { id: 'h-12', date: '2026-07-31', time: '07:45 AM', doseSlot: 'Morning', status: 'taken' },
        ],
      },
    ],
    weeklyVitalsHistory: [
      { day: 'Mon', bpSystolic: 152, glucose: 190, steps: 3200 },
      { day: 'Tue', bpSystolic: 146, glucose: 178, steps: 4100 },
      { day: 'Wed', bpSystolic: 149, glucose: 185, steps: 3800 },
      { day: 'Thu', bpSystolic: 144, glucose: 172, steps: 5200 },
      { day: 'Fri', bpSystolic: 148, glucose: 182, steps: 4600 },
      { day: 'Sat', bpSystolic: 142, glucose: 168, steps: 6100 },
      { day: 'Sun', bpSystolic: 145, glucose: 175, steps: 5400 },
    ],
    caregiverName: 'Mark Vance',
    caregiverRelation: 'Son & Primary Caregiver',
    emergencyContacts: [
      {
        id: 'ec-1',
        name: 'Mark Vance',
        relation: 'Son (Primary Caregiver)',
        phone: '+1 (555) 234-5678',
        email: 'mark.vance@example.com',
        isPrimary: true,
        notes: 'Lives 10 minutes away. Has home security key & medical proxy.',
      },
      {
        id: 'ec-2',
        name: 'Sarah Vance-Miller',
        relation: 'Daughter',
        phone: '+1 (555) 876-5432',
        email: 'sarah.vance@example.com',
        isPrimary: false,
        notes: 'Secondary contact. Available weekends and evenings.',
      },
      {
        id: 'ec-3',
        name: 'Dr. Arthur Pendelton',
        relation: 'Primary Care Physician',
        phone: '+1 (555) 990-1122',
        email: 'dr.pendelton@cityhealth.org',
        isPrimary: false,
        notes: 'St. Jude Health Clinic, Room 304. Direct nurse desk: ext 402.',
      },
      {
        id: 'ec-4',
        name: 'City Medical Emergency Dept',
        relation: 'Hospital Emergency Room',
        phone: '911 / +1 (555) 911-0000',
        isPrimary: false,
        notes: 'Nearest ER: 2.5 miles (City General Hospital).',
      },
    ],
    pendingTests: [
      {
        id: 'pt-1',
        testName: 'HbA1c & Fasting Lipid Profile',
        category: 'Lab Test',
        orderedBy: 'Dr. Arthur Pendelton',
        dueDate: '2026-08-05',
        status: 'Scheduled',
        instructions: 'Fasting required for 10-12 hours prior to lab blood draw. Drink water normally.',
        facilityLocation: 'Quest Diagnostics - Main Street Branch',
      },
      {
        id: 'pt-2',
        testName: 'Urine Albumin-to-Creatinine Ratio (uACR)',
        category: 'Lab Test',
        orderedBy: 'Dr. Arthur Pendelton',
        dueDate: '2026-08-08',
        status: 'Pending Sample',
        instructions: 'First morning urine sample container provided.',
        facilityLocation: 'City Health Lab',
      },
      {
        id: 'pt-3',
        testName: 'Dilated Retinal Eye Screening',
        category: 'Specialist Screening',
        orderedBy: 'Dr. Arthur Pendelton',
        dueDate: '2026-08-15',
        status: 'Scheduled',
        instructions: 'Dilating drops will blur vision for 2-3 hours. Caregiver escort required to drive home.',
        facilityLocation: 'VisionCare Specialists Clinic',
      },
    ],
    upcomingReferrals: [
      {
        id: 'ref-101',
        specialty: 'Endocrinology & Diabetes Care',
        specialistName: 'Dr. Meera Sharma, MD',
        reason: 'Uncontrolled Type 2 Diabetes (HbA1c 8.6%) & Insulin Sensitivity Optimization',
        status: 'Authorized',
        appointmentDate: '2026-08-22',
        clinicPhone: '+1 (555) 432-1000',
        urgency: 'Urgent',
        referralId: 'REF-2026-8819',
      },
      {
        id: 'ref-102',
        specialty: 'Cardiology (Hypertension Specialist)',
        specialistName: 'Dr. Robert Lawson, MD',
        reason: 'Stage 2 Hypertension (148/94 mmHg average) & Cardiorenal Risk Assessment',
        status: 'Action Needed',
        clinicPhone: '+1 (555) 321-9988',
        urgency: 'Routine',
        referralId: 'REF-2026-9041',
      },
    ],
    upcomingAppointments: [
      {
        id: 'apt-1',
        doctorName: 'Dr. Arthur Pendelton',
        specialty: 'Primary Care Physician',
        date: '2026-08-10',
        time: '10:30 AM',
        location: 'City Health Center - Suite 304',
        purpose: 'Bi-Monthly Diabetes & BP Regimen Follow-up',
        status: 'Confirmed',
        prepInstructions: 'Bring morning blood glucose log and home BP cuff readings from past 14 days.',
        clinicPhone: '+1 (555) 990-1122',
      },
      {
        id: 'apt-2',
        doctorName: 'Dr. Meera Sharma',
        specialty: 'Endocrinology Specialist',
        date: '2026-08-22',
        time: '02:00 PM',
        location: 'Endocrine Specialty Institute - Building B',
        purpose: 'Specialist Consultation for Glycemic Control',
        status: 'Confirmed',
        prepInstructions: 'Bring recent HbA1c lab report and complete list of current medications.',
        clinicPhone: '+1 (555) 432-1000',
      },
    ],
    caregiverAlerts: [
      {
        id: 'ca-1',
        date: '2026-07-30',
        severity: 'Warning',
        title: 'Missed Evening Metformin XR Dose',
        message: 'Patient log indicates evening dose was skipped on July 30.',
        resolved: true,
        resolvedAt: '2026-07-31 08:30 AM',
        category: 'Adherence',
      },
      {
        id: 'ca-2',
        date: '2026-07-28',
        severity: 'Critical',
        title: 'Elevated Morning BP Reading (150/96 mmHg)',
        message: 'Systolic blood pressure exceeded 145 mmHg threshold. Doctor notified via EHR flag.',
        resolved: false,
        category: 'Vitals',
      },
      {
        id: 'ca-3',
        date: '2026-07-25',
        severity: 'Warning',
        title: 'Refill Warning: Empagliflozin Low Supply',
        message: 'Only 9 days of Empagliflozin remaining. Pharmacy order recommended.',
        resolved: false,
        category: 'Adherence',
      },
    ],
    caregiverReminders: [
      {
        id: 'cr-1',
        time: '08:00 AM',
        title: 'Check Mom\'s Fasting Blood Glucose',
        description: 'Ensure glucose meter reading is logged before breakfast.',
        category: 'Vitals',
        completed: true,
        frequency: 'Daily',
      },
      {
        id: 'cr-2',
        time: '08:30 AM',
        title: 'Confirm Metformin XR & Empagliflozin Morning Dose',
        description: 'Verify pills taken with breakfast.',
        category: 'Medication',
        completed: true,
        frequency: 'Daily',
      },
      {
        id: 'cr-3',
        time: '02:00 PM',
        title: 'Order Pharmacy Refill for Empagliflozin 10mg',
        description: 'Contact Walgreens Pharmacy (Rx #8841029) for delivery or pickup.',
        category: 'Refill',
        completed: false,
        frequency: 'Once',
      },
      {
        id: 'cr-4',
        time: '08:00 PM',
        title: 'Assist with Evening BP Measurement',
        description: 'Measure sitting blood pressure after 5 mins rest.',
        category: 'Vitals',
        completed: false,
        frequency: 'Daily',
      },
    ],
    preferredLanguage: 'Gujarati',
    region: 'Gujarat',
    religion: 'Hindu',
    foodPreference: 'Vegetarian',
    festivalCalendar: ['Navratri', 'Diwali', 'Uttrayan'],
    occupation: 'Textile Business Owner',
    incomeCategory: 'Upper Middle',
  },
  {
    id: 'p-102',
    mrn: 'MRN-773920',
    name: 'Marcus Brody',
    age: 46,
    gender: 'Male',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    riskLevel: 'Moderate',
    riskScore: 58,
    primaryDoctor: 'Dr. Arthur Pendelton, MD',
    conditions: ['Pre-diabetes', 'Hyperlipidemia', 'Sedentary Lifestyle'],
    lastAssessmentDate: '2026-07-29',
    vitals: {
      bpSystolic: 132,
      bpDiastolic: 86,
      heartRate: 76,
      bmi: 28.2,
      glucose: 114,
      hba1c: 6.2,
      ldl: 142,
      weightKg: 89.0,
    },
    pendingReferral: false,
    recentActivity: [
      {
        id: 'act-10',
        date: '2026-07-29',
        type: 'assessment',
        title: 'Routine Health Check & Risk Assessment',
        description: 'CDSS flagged early Metabolic Syndrome markers. Lifestyle modification counseling prescribed.',
        badgeText: 'Moderate Risk',
        badgeType: 'warning',
      },
      {
        id: 'act-11',
        date: '2026-07-20',
        type: 'lab',
        title: 'Fasting Lipid Profile',
        description: 'Total cholesterol 225 mg/dL, Triglycerides 190 mg/dL.',
        badgeText: 'Elevated Lipids',
        badgeType: 'info',
      },
    ],
    medications: [
      {
        id: 'm-10',
        name: 'Rosuvastatin',
        strength: '10 mg',
        dosage: '10mg',
        frequency: 'Once daily (Night)',
        schedule: { morning: false, afternoon: false, night: true },
        timing: 'After Food',
        startDate: '2026-06-01',
        endDate: '2026-12-01',
        duration: '180 Days',
        purpose: 'Lipid Regulation & Plaque Stabilization',
        sideEffects: ['Mild muscle discomfort'],
        refillReminder: true,
        refillDate: '2026-08-18',
        refillPillsRemaining: 18,
        missedDoseReminder: true,
        reminderTimes: ['09:00 PM'],
        takenToday: true,
        takenTimesToday: { night: true },
        historyLogs: [
          { id: 'hm-1', date: '2026-08-01', time: '09:05 PM', doseSlot: 'Night', status: 'taken' },
        ],
      },
      {
        id: 'm-11',
        name: 'Omega-3 Fatty Acids',
        strength: '1000 mg',
        dosage: '1000mg',
        frequency: 'Twice daily',
        schedule: { morning: true, afternoon: false, night: true },
        timing: 'With Food',
        startDate: '2026-05-15',
        endDate: '2026-11-15',
        duration: '180 Days',
        purpose: 'Triglyceride Reduction',
        sideEffects: ['Fishy taste'],
        refillReminder: false,
        refillDate: '2026-09-01',
        refillPillsRemaining: 30,
        missedDoseReminder: true,
        reminderTimes: ['08:00 AM', '08:00 PM'],
        takenToday: true,
        takenTimesToday: { morning: true, night: true },
        historyLogs: [
          { id: 'hm-2', date: '2026-08-01', time: '08:10 AM', doseSlot: 'Morning', status: 'taken' },
        ],
      },
    ],
    weeklyVitalsHistory: [
      { day: 'Mon', bpSystolic: 134, glucose: 118, steps: 6200 },
      { day: 'Tue', bpSystolic: 130, glucose: 112, steps: 7500 },
      { day: 'Wed', bpSystolic: 135, glucose: 115, steps: 5800 },
      { day: 'Thu', bpSystolic: 131, glucose: 110, steps: 8100 },
      { day: 'Fri', bpSystolic: 132, glucose: 114, steps: 7200 },
      { day: 'Sat', bpSystolic: 128, glucose: 108, steps: 9400 },
      { day: 'Sun', bpSystolic: 130, glucose: 112, steps: 8600 },
    ],
  },
  {
    id: 'p-103',
    mrn: 'MRN-310492',
    name: 'Sarah Chen',
    age: 34,
    gender: 'Female',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    riskLevel: 'Low',
    riskScore: 18,
    primaryDoctor: 'Dr. Arthur Pendelton, MD',
    conditions: ['Optimal Vital Range', 'Family History of Hypertension'],
    lastAssessmentDate: '2026-07-30',
    vitals: {
      bpSystolic: 116,
      bpDiastolic: 74,
      heartRate: 68,
      bmi: 22.1,
      glucose: 88,
      hba1c: 5.1,
      ldl: 92,
      weightKg: 58.2,
    },
    pendingReferral: false,
    recentActivity: [
      {
        id: 'act-20',
        date: '2026-07-30',
        type: 'assessment',
        title: 'Annual Wellness Screening',
        description: 'All biomarkers within normal range. Maintain current aerobic exercise regime.',
        badgeText: 'Low Risk',
        badgeType: 'success',
      },
    ],
    medications: [
      {
        id: 'm-20',
        name: 'Multivitamin Complex',
        strength: '1 Tablet',
        dosage: '1 Tablet',
        frequency: 'Once daily',
        schedule: { morning: true, afternoon: false, night: false },
        timing: 'After Food',
        startDate: '2026-01-01',
        endDate: '2026-12-31',
        duration: '365 Days',
        purpose: 'Micronutrient Support',
        sideEffects: [],
        refillReminder: false,
        missedDoseReminder: false,
        takenToday: true,
        takenTimesToday: { morning: true },
        historyLogs: [],
      },
      {
        id: 'm-21',
        name: 'Vitamin D3',
        strength: '2000 IU',
        dosage: '2000 IU',
        frequency: 'Once daily',
        schedule: { morning: true, afternoon: false, night: false },
        timing: 'After Food',
        startDate: '2026-02-01',
        endDate: '2026-08-01',
        duration: '180 Days',
        purpose: 'Bone Density & Immunity',
        sideEffects: [],
        refillReminder: false,
        missedDoseReminder: true,
        takenToday: true,
        takenTimesToday: { morning: true },
        historyLogs: [],
      },
    ],
    weeklyVitalsHistory: [
      { day: 'Mon', bpSystolic: 118, glucose: 90, steps: 10200 },
      { day: 'Tue', bpSystolic: 115, glucose: 86, steps: 11500 },
      { day: 'Wed', bpSystolic: 116, glucose: 88, steps: 9800 },
      { day: 'Thu', bpSystolic: 114, glucose: 87, steps: 12100 },
      { day: 'Fri', bpSystolic: 117, glucose: 89, steps: 10600 },
      { day: 'Sat', bpSystolic: 115, glucose: 85, steps: 13400 },
      { day: 'Sun', bpSystolic: 116, glucose: 88, steps: 11200 },
    ],
  },
  {
    id: 'p-104',
    mrn: 'MRN-902184',
    name: 'David Miller',
    age: 62,
    gender: 'Male',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    riskLevel: 'High',
    riskScore: 78,
    primaryDoctor: 'Dr. Arthur Pendelton, MD',
    conditions: ['Coronary Artery Disease Risk', 'Type 2 Diabetes', 'Obesity Class I'],
    lastAssessmentDate: '2026-07-26',
    vitals: {
      bpSystolic: 142,
      bpDiastolic: 90,
      heartRate: 78,
      bmi: 32.8,
      glucose: 165,
      hba1c: 7.9,
      ldl: 155,
      weightKg: 98.4,
    },
    pendingReferral: true,
    referralSpecialist: 'Cardiology',
    recentActivity: [
      {
        id: 'act-30',
        date: '2026-07-26',
        type: 'referral',
        title: 'Echocardiogram & Cardiac Consult Triggered',
        description: 'Exertional dyspnea with high ASCVD score. Urgent cardiology evaluation scheduled.',
        badgeText: 'Pending Referral',
        badgeType: 'danger',
      },
    ],
    medications: [
      {
        id: 'm-30',
        name: 'Amlodipine',
        strength: '10 mg',
        dosage: '10mg',
        frequency: 'Daily morning',
        schedule: { morning: true, afternoon: false, night: false },
        timing: 'Before Food',
        startDate: '2026-03-01',
        endDate: '2026-09-01',
        duration: '180 Days',
        purpose: 'Calcium Channel Blocker for Hypertension',
        sideEffects: ['Ankle swelling', 'Flushing'],
        refillReminder: true,
        refillDate: '2026-08-05',
        refillPillsRemaining: 4,
        missedDoseReminder: true,
        reminderTimes: ['08:00 AM'],
        takenToday: false,
        takenTimesToday: { morning: false },
        historyLogs: [],
      },
      {
        id: 'm-31',
        name: 'Glipizide',
        strength: '5 mg',
        dosage: '5mg',
        frequency: 'Twice daily',
        schedule: { morning: true, afternoon: false, night: true },
        timing: 'Before Food',
        startDate: '2026-05-01',
        endDate: '2026-11-01',
        duration: '180 Days',
        purpose: 'Sulfonylurea for Diabetes Blood Sugar Reduction',
        sideEffects: ['Hypoglycemia risk if meal missed'],
        refillReminder: true,
        refillDate: '2026-08-25',
        refillPillsRemaining: 24,
        missedDoseReminder: true,
        reminderTimes: ['07:30 AM', '07:30 PM'],
        takenToday: true,
        takenTimesToday: { morning: true, night: false },
        historyLogs: [],
      },
    ],
    weeklyVitalsHistory: [
      { day: 'Mon', bpSystolic: 145, glucose: 170, steps: 4100 },
      { day: 'Tue', bpSystolic: 140, glucose: 162, steps: 4800 },
      { day: 'Wed', bpSystolic: 144, glucose: 168, steps: 3900 },
      { day: 'Thu', bpSystolic: 141, glucose: 160, steps: 5100 },
      { day: 'Fri', bpSystolic: 142, glucose: 165, steps: 4500 },
      { day: 'Sat', bpSystolic: 139, glucose: 158, steps: 5800 },
      { day: 'Sun', bpSystolic: 142, glucose: 165, steps: 4900 },
    ],
  },
  {
    id: 'p-105',
    mrn: 'MRN-551029',
    name: 'Priya Sharma',
    age: 41,
    gender: 'Female',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    riskLevel: 'Low',
    riskScore: 24,
    primaryDoctor: 'Dr. Arthur Pendelton, MD',
    conditions: ['Mild Thyroid Hormone Imbalance', 'Healthy Metabolic Markers'],
    lastAssessmentDate: '2026-07-22',
    vitals: {
      bpSystolic: 120,
      bpDiastolic: 78,
      heartRate: 72,
      bmi: 23.5,
      glucose: 94,
      hba1c: 5.4,
      ldl: 104,
      weightKg: 62.0,
    },
    pendingReferral: false,
    recentActivity: [
      {
        id: 'act-40',
        date: '2026-07-22',
        type: 'lab',
        title: 'Thyroid Function Test (TSH / Free T4)',
        description: 'TSH slightly elevated at 4.2 mIU/L. Follow up in 3 months.',
        badgeText: 'Stable',
        badgeType: 'info',
      },
    ],
    medications: [
      {
        id: 'm-40',
        name: 'Levothyroxine',
        strength: '50 mcg',
        dosage: '50mcg',
        frequency: 'Once daily before breakfast',
        schedule: { morning: true, afternoon: false, night: false },
        timing: 'Before Food',
        startDate: '2026-01-15',
        endDate: '2027-01-15',
        duration: '365 Days',
        purpose: 'Thyroid Hormone Replacement',
        sideEffects: ['Heart palpitations if over-dosed'],
        refillReminder: true,
        refillDate: '2026-08-30',
        refillPillsRemaining: 29,
        missedDoseReminder: true,
        reminderTimes: ['06:30 AM'],
        takenToday: true,
        takenTimesToday: { morning: true },
        historyLogs: [],
      },
    ],
    weeklyVitalsHistory: [
      { day: 'Mon', bpSystolic: 122, glucose: 96, steps: 8500 },
      { day: 'Tue', bpSystolic: 119, glucose: 92, steps: 9100 },
      { day: 'Wed', bpSystolic: 120, glucose: 94, steps: 8800 },
      { day: 'Thu', bpSystolic: 118, glucose: 91, steps: 9400 },
      { day: 'Fri', bpSystolic: 121, glucose: 95, steps: 8900 },
      { day: 'Sat', bpSystolic: 119, glucose: 90, steps: 10500 },
      { day: 'Sun', bpSystolic: 120, glucose: 94, steps: 9200 },
    ],
    preferredLanguage: 'Hindi',
    region: 'North India',
    religion: 'Hindu',
    foodPreference: 'Vegetarian',
    festivalCalendar: ['Navratri', 'Diwali', 'Holi'],
    occupation: 'School Teacher',
    incomeCategory: 'Middle',
  },
];

export const MOCK_LAB_REPORTS: LabReport[] = [
  {
    id: 'rep-001',
    patientId: 'p-101',
    patientName: 'Eleanor Vance',
    title: 'Comprehensive Metabolic Panel & Lipid Profile',
    category: 'Lab Test',
    uploadDate: '2026-07-28',
    fileSize: '2.4 MB PDF',
    status: 'Requires Attention',
    summary: 'Elevated fasting blood glucose (182 mg/dL) and HbA1c (8.6%). Lipid panel demonstrates high LDL (168 mg/dL) and low HDL (38 mg/dL). High cardiovascular risk indication.',
    abnormalItems: [
      { parameter: 'HbA1c', value: '8.6 %', normalRange: '< 5.7 %', severity: 'High' },
      { parameter: 'Fasting Glucose', value: '182 mg/dL', normalRange: '70 - 99 mg/dL', severity: 'High' },
      { parameter: 'LDL Cholesterol', value: '168 mg/dL', normalRange: '< 100 mg/dL', severity: 'High' },
      { parameter: 'ALT (Liver Enzyme)', value: '54 U/L', normalRange: '7 - 35 U/L', severity: 'High' },
    ],
  },
  {
    id: 'rep-002',
    patientId: 'p-102',
    patientName: 'Marcus Brody',
    title: 'Lipid Profile & High-Sensitivity CRP',
    category: 'Lab Test',
    uploadDate: '2026-07-20',
    fileSize: '1.8 MB PDF',
    status: 'Reviewed',
    summary: 'Moderate elevation in triglycerides and total cholesterol. hs-CRP elevated at 2.8 mg/L indicating borderline systemic inflammatory response.',
    abnormalItems: [
      { parameter: 'Triglycerides', value: '190 mg/dL', normalRange: '< 150 mg/dL', severity: 'High' },
      { parameter: 'hs-CRP', value: '2.8 mg/L', normalRange: '< 1.0 mg/L', severity: 'High' },
    ],
  },
  {
    id: 'rep-003',
    patientId: 'p-104',
    patientName: 'David Miller',
    title: '12-Lead Resting Electrocardiogram (ECG)',
    category: 'ECG',
    uploadDate: '2026-07-26',
    fileSize: '3.1 MB PDF',
    status: 'Requires Attention',
    summary: 'Sinus rhythm with sinus bradycardia. Mild left ventricular hypertrophy patterns noted. AI suggests correlation with chronic Stage 2 hypertension.',
    abnormalItems: [
      { parameter: 'QTc Interval', value: '448 ms', normalRange: '< 440 ms', severity: 'High' },
      { parameter: 'Sokolow-Lyon Index', value: '38 mm', normalRange: '< 35 mm', severity: 'High' },
    ],
  },
];

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'rec-1',
    category: 'Diet & Nutrition',
    title: 'Adopt Mediterranean-Style Low-Glycemic Index Diet',
    description: 'Reduce refined carbohydrates and saturated fats. Increase dietary soluble fiber to improve glycemic variability and lower LDL cholesterol.',
    priority: 'High',
    actionableStep: 'Target < 45g carbohydrate per meal and include extra virgin olive oil daily.',
  },
  {
    id: 'rec-2',
    category: 'Exercise & Fitness',
    title: 'Target 150 Mins Moderate Aerobic Physical Activity',
    description: 'Brisk walking, cycling, or swimming 30 minutes, 5 days per week enhances insulin sensitivity and arterial compliance.',
    priority: 'High',
    actionableStep: 'Schedule 30-min morning walks before work, tracking 7,000+ daily steps.',
  },
  {
    id: 'rec-3',
    category: 'Screening',
    title: 'Schedule FibroScan / Abdominal Ultrasound for NAFLD',
    description: 'Due to elevated ALT liver enzymes and metabolic markers, screen for non-alcoholic fatty liver disease stage.',
    priority: 'Medium',
    actionableStep: 'Discuss referral for liver elastography during next clinical follow-up.',
  },
  {
    id: 'rec-4',
    category: 'Medication',
    title: 'Blood Pressure Home Log Monitoring',
    description: 'Record twice daily blood pressure readings (morning and evening) in the patient dashboard.',
    priority: 'High',
    actionableStep: 'Log readings daily at 8:00 AM and 8:00 PM sitting quietly for 5 mins.',
  },
];
